# --- USUÁRIOS ---
user = User.find_or_create_by!(email: "test@test.com") do |u|
  u.password = "123456"
end
user.update_columns(first_name: "João") if user.first_name.blank?

ana    = User.find_or_create_by!(email: "ana@test.com")    { |u| u.password = "123456"; u.first_name = "Ana" }
carlos = User.find_or_create_by!(email: "carlos@test.com") { |u| u.password = "123456"; u.first_name = "Carlos" }

joao_id   = user.id
ana_id    = ana.id
carlos_id = carlos.id

# --- TODOS OS LUGARES (upsert em bloco) ---
now = Time.current

all_places = [
  { name: "Bar do Zé",              address: "Rua das Flores, 123, Rio de Janeiro" },
  { name: "Restaurante da Maria",   address: "Av. Atlântica, 456, Rio de Janeiro" },
  { name: "Café Central",           address: "Rua XV de Novembro, 789, Rio de Janeiro" },
  { name: "Lapa Safe Bar",          address: "Av. Mem de Sá, 10, Rio de Janeiro" },
  { name: "Club Alerta",            address: "Rua da Passagem, 50, Rio de Janeiro" },
  { name: "Bar de Teste Misto",     address: "Rua Voluntários da Pátria, 100, Rio de Janeiro" },
  { name: "Bar Bukowski",           address: "Rua Almirante Gonçalves, 50, Copacabana, Rio de Janeiro" },
  { name: "Club Fosfobox",          address: "Rua Siqueira Campos, 143, Copacabana, Rio de Janeiro" },
  { name: "Barzin",                 address: "Rua Farme de Amoedo, 87, Ipanema, Rio de Janeiro" },
  { name: "La Carioca Cevicheria",  address: "Rua Dias Ferreira, 610, Leblon, Rio de Janeiro" },
  { name: "Bar Urca",               address: "Rua Cândido Gaffrée, 205, Urca, Rio de Janeiro" },
  { name: "Empório 37",             address: "Rua Dias Ferreira, 37, Leblon, Rio de Janeiro" },
  { name: "Cine Joia",              address: "Praça Tiradentes, 79, Centro, Rio de Janeiro" },
  { name: "Casa da Matriz",         address: "Rua Henrique Novaes, 107, Botafogo, Rio de Janeiro" },
  { name: "Bar dos Descasados",     address: "Rua Áurea, 80, Santa Teresa, Rio de Janeiro" },
  { name: "Mirindiba",              address: "Rua Paschoal Carlos Magno, 138, Santa Teresa, Rio de Janeiro" },
  { name: "Choperia Bracarense",    address: "Rua José Linhares, 85, Leblon, Rio de Janeiro" },
  { name: "Garota de Ipanema Bar",  address: "Rua Vinicius de Moraes, 49, Ipanema, Rio de Janeiro" },
  { name: "The Week Rio",           address: "Rua Sacadura Cabral, 154, Saúde, Rio de Janeiro" },
  { name: "Leviano Bar",            address: "Av. Bartolomeu Mitre, 370, Leblon, Rio de Janeiro" },
  { name: "Jobi Bar",               address: "Av. Ataulfo de Paiva, 1166, Leblon, Rio de Janeiro" },
  { name: "Lapa 40 Graus",          address: "Rua do Riachuelo, 97, Lapa, Rio de Janeiro" },
  { name: "Bar do Mineiro",         address: "Rua Paschoal Carlos Magno, 99, Santa Teresa, Rio de Janeiro" },
  { name: "Venga!",                 address: "Rua Farme de Amoedo, 41, Ipanema, Rio de Janeiro" },
  { name: "Clube dos Democratas",   address: "Rua Riachuelo, 91, Lapa, Rio de Janeiro" },
  { name: "Scenarium",              address: "Rua do Lavradio, 20, Lapa, Rio de Janeiro" },
  { name: "Bar Lagoa",              address: "Av. Epitácio Pessoa, 1674, Lagoa, Rio de Janeiro" },
  { name: "Palaphita Kitch",        address: "Av. Epitácio Pessoa, Quiosque 20, Lagoa, Rio de Janeiro" },
  { name: "Melt Bar",               address: "Rua General Urquiza, 102, Leblon, Rio de Janeiro" },
  { name: "Maze Inn Bar",           address: "Rua Tavares Bastos, 414, Catete, Rio de Janeiro" },
  { name: "Baixo Gávea",            address: "Praça Santos Dumont, Gávea, Rio de Janeiro" },
  { name: "Bar Brahma",             address: "Av. São João, 677, Centro, São Paulo, SP" },
  { name: "A Barulheira",           address: "Rua Frei Caneca, 916, Consolação, São Paulo, SP" },
  { name: "The Blue Pub",           address: "Rua Augusta, 765, Consolação, São Paulo, SP" },
  { name: "Clube Buena Vista",      address: "Rua Aspicuelta, 58, Vila Madalena, São Paulo, SP" },
  { name: "Bar Balcão",             address: "Rua Dr. Melo Alves, 150, Jardins, São Paulo, SP" },
  { name: "Pelourinho Bar",         address: "Largo do Pelourinho, 12, Salvador, BA" },
  { name: "Beco dos Artistas",      address: "Rua das Laranjeiras, 15, Barra, Salvador, BA" },
  { name: "Bar do Reggae",          address: "Rua Portas do Carmo, 21, Salvador, BA" },
  { name: "Boteco da Praia",        address: "Av. Presidente Vargas, 10, Ponta Negra, Manaus, AM" },
  { name: "Studio 5 Club",          address: "Av. Constantino Nery, 3399, Chapada, Manaus, AM" },
  { name: "Bar do Ferreira",        address: "Rua da Aurora, 463, Boa Vista, Recife, PE" },
  { name: "Baiúca Bar",             address: "Rua Mamede Simões, 80, Boa Viagem, Recife, PE" },
  { name: "Armazém 5",              address: "Rua Professor Walter Baumgarten, 500, Fortaleza, CE" },
  { name: "Boteco Praia de Iracema", address: "Rua dos Tabajaras, 325, Praia de Iracema, Fortaleza, CE" },
  { name: "Casa de Shows Náutico",  address: "Av. Boa Viagem, 4070, Boa Viagem, Recife, PE" },
  { name: "Opinião",                address: "Rua José do Patrocínio, 834, Cidade Baixa, Porto Alegre, RS" },
  { name: "Bar Ocidente",           address: "Av. Osvaldo Aranha, 960, Bom Fim, Porto Alegre, RS" },
  { name: "Toca da Coruja",         address: "Rua Padre Chagas, 342, Moinhos de Vento, Porto Alegre, RS" },
  { name: "Razzmatazz Curitiba",    address: "Rua Mateus Leme, 1200, São Francisco, Curitiba, PR" },
  { name: "Bar do Victor",          address: "Rua 24 Horas, 52, Centro, Curitiba, PR" },
  { name: "Bar Beirute BH",         address: "Rua Antônio de Albuquerque, 514, Savassi, Belo Horizonte, MG" },
  { name: "Café com Letras",        address: "Rua Antônio de Albuquerque, 781, Savassi, Belo Horizonte, MG" },
  { name: "Bukowski BH",            address: "Rua Fernandes Tourinho, 358, Savassi, Belo Horizonte, MG" },
  { name: "Manifesto Bar",          address: "Rua Antônio de Albuquerque, 399, Savassi, Belo Horizonte, MG" },
  { name: "Bar Brasília",           address: "SCLS 412, Bloco C, Asa Sul, Brasília, DF" },
  { name: "Clube do Choro",         address: "SEPS 713/913, Asa Sul, Brasília, DF" },
  { name: "Antro Pub",              address: "CLN 408, Bloco D, Asa Norte, Brasília, DF" },
  { name: "Hangar 110",             address: "SHS Quadra 6, Setor Hoteleiro Sul, Brasília, DF" },
  { name: "John Bull Pub",          address: "Rua Felipe Schmidt, 58, Centro, Florianópolis, SC" },
  { name: "Bar do Ataliba",         address: "Rua Bocaiúva, 1508, Centro, Florianópolis, SC" },
  { name: "Dado Bier Floripa",      address: "Rodovia SC-401, 2356, Santo Antônio, Florianópolis, SC" },
  { name: "Goianésia Bar",          address: "Rua 3, 840, Setor Oeste, Goiânia, GO" },
  { name: "Aramará Bar",            address: "Rua T-37, 1200, Setor Bueno, Goiânia, GO" },
  { name: "Ver-o-Peso Bar",         address: "Av. Castilhos França, 180, Cidade Velha, Belém, PA" },
  { name: "Estação das Docas",      address: "Bulevar Castilhos França, Campina, Belém, PA" },
  { name: "Bar do Meio",            address: "Rua Chile, 120, Praia do Meio, Natal, RN" },
  { name: "Barcas Bar",             address: "Av. Presidente Café Filho, 10, Praia do Forte, Natal, RN" },
  { name: "Slow Bar",               address: "Rua Coração de Jesus, 46, Centro, João Pessoa, PB" },
  { name: "Café Epitácio",          address: "Av. Epitácio Pessoa, 4946, Tambaú, João Pessoa, PB" },
  { name: "Jaraguá Bar",            address: "Rua Sá e Albuquerque, 30, Jaraguá, Maceió, AL" },
  { name: "Bar do Francis",         address: "Rua Engenheiro Paulo Brandão Nogueira, 80, Jatiúca, Maceió, AL" },
  { name: "Buritis Bar",            address: "Rua Barão do Rio Branco, 15, Centro, Campo Grande, MS" },
  { name: "Pub 540",                address: "Av. Afonso Pena, 2270, Centro, Campo Grande, MS" },
  { name: "Bar Central Vitória",    address: "Rua Sete de Setembro, 507, Centro, Vitória, ES" },
  { name: "Bohemia Club",           address: "Rua Joaquim Lírio, 80, Praia do Canto, Vitória, ES" },
  { name: "Antigamente Bar",        address: "Rua da Paz, 230, Centro Histórico, São Luís, MA" },
  { name: "Bar do Nelson",          address: "Av. Litorânea, 12, Calhau, São Luís, MA" },
  { name: "Casa Mágica",            address: "Rua do Giz, 42, Centro Histórico, São Luís, MA" },
  { name: "Quixabeira Bar",         address: "Rua das Laranjeiras, 311, Pituba, Salvador, BA" },
  { name: "Ó do Borogodó",          address: "Rua Inácio Acioli, 1, Lapa, São Paulo, SP" }
]

# Apenas insere lugares que ainda não existem (sem precisar de unique index)
existing_names = Place.pluck(:name).to_set
new_places = all_places.reject { |p| existing_names.include?(p[:name]) }
Place.insert_all(new_places.map { |p| p.merge(created_at: now, updated_at: now) }) if new_places.any?

# Geocodifica via Mapbox os lugares sem coordenadas
Place.where(latitude: nil).find_each do |place|
  place.geocode
  place.update_columns(latitude: place.latitude, longitude: place.longitude) if place.latitude.present?
end

# Carrega mapa name->id em memória (1 query)
place_ids = Place.pluck(:name, :id).to_h

# Carrega reports existentes em memória (1 query)
existing_reports = Report.pluck(:place_id, :user_id).map { |pid, uid| [pid, uid] }.to_set

# --- TODOS OS REPORTS ---
all_reports = [
  # Bar do Zé
  { place: "Bar do Zé",              user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Ótimo lugar, ambiente muito agradável e acolhedor para todos os públicos." },
  { place: "Bar do Zé",              user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Muito seguro, equipe sempre presente e atenta a qualquer situação." },
  # Lapa Safe Bar
  { place: "Lapa Safe Bar",          user_id: joao_id,   cat: "Geral",       status: "positive", desc: "Muito seguro, ambiente tranquilo e equipe sempre presente para ajudar." },
  { place: "Lapa Safe Bar",          user_id: ana_id,    cat: "Assédio",     status: "positive", desc: "Equipe nota 10, sempre atentos e prontos para intervir em qualquer situação." },
  # Club Alerta
  { place: "Club Alerta",            user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Tive problemas sérios aqui, situação de assédio sem nenhuma intervenção da equipe." },
  { place: "Club Alerta",            user_id: ana_id,    cat: "Segurança",   status: "negative", desc: "Falta iluminação e a revista na entrada é completamente inexistente, muito perigoso." },
  # Bar de Teste Misto
  { place: "Bar de Teste Misto",     user_id: joao_id,   cat: "Geral",       status: "positive", desc: "O lugar é legal no geral, boa música e atendimento razoável durante a semana." },
  { place: "Bar de Teste Misto",     user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Ambiente pouco inclusivo, percebi claramente discriminação por parte de alguns funcionários." },
  # RJ places
  { place: "Bar Bukowski",           user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Ambiente super acolhedor e diverso, me senti muito à vontade a noite toda." },
  { place: "Club Fosfobox",          user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Segurança excelente na porta, sem problemas durante toda a noite." },
  { place: "Club Fosfobox",          user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Presenciei uma situação desconfortável perto da pista de dança." },
  { place: "Barzin",                 user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Lugar muito inclusivo e amigável para a comunidade LGBTQ+." },
  { place: "La Carioca Cevicheria",  user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Nunca tive nenhum problema aqui, equipe sempre atenta." },
  { place: "Bar Urca",               user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Vista linda e ambiente tranquilo, ótimo para ir com amigos." },
  { place: "Empório 37",             user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Fui mal atendido depois que o funcionário percebeu que eu era gay, situação constrangedora." },
  { place: "Empório 37",             user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Geralmente tranquilo e agradável, mas a experiência pode variar bastante dependendo do dia." },
  { place: "Cine Joia",              user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Shows ótimos e ambiente seguro, staff muito presente." },
  { place: "Casa da Matriz",         user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Sofri assédio verbal e ninguém da equipe tomou nenhuma atitude." },
  { place: "Bar dos Descasados",     user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Ambiente boêmio e muito acolhedor, me senti em casa." },
  { place: "Mirindiba",              user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Lugar charmoso e muito tranquilo, fui várias vezes e nunca tive nenhum incidente." },
  { place: "Choperia Bracarense",    user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Percebi olhares e comentários preconceituosos de outros clientes." },
  { place: "Garota de Ipanema Bar",  user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Clássico carioca, ambiente relaxado e sem julgamentos." },
  { place: "The Week Rio",           user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Estrutura de segurança impecável, me senti muito protegido a noite toda." },
  { place: "The Week Rio",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Melhor clube LGBTQ+ do Rio, ambiente muito inclusivo e acolhedor." },
  { place: "Leviano Bar",            user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Assédio constante por parte de um grupo de clientes sem intervenção da equipe." },
  { place: "Jobi Bar",               user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Botequim tradicional, pessoal muito simpático e sem frescura." },
  { place: "Lapa 40 Graus",          user_id: joao_id,   cat: "Violência",   status: "negative", desc: "Briga séria dentro do estabelecimento e segurança demorou muito para agir." },
  { place: "Bar do Mineiro",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Comida boa e ambiente familiar, sem nenhuma ocorrência." },
  { place: "Venga!",                 user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Bar LGBTQ+ friendly, staff muito atencioso e ambiente seguro." },
  { place: "Clube dos Democratas",   user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Baile tradicional, movimento intenso mas equipe bem preparada." },
  { place: "Scenarium",              user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Funcionário foi grosseiro ao ver dois homens se beijando, situação horrível." },
  { place: "Scenarium",              user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Decoração incrível e samba ao vivo imperdível, uma experiência única." },
  { place: "Bar Lagoa",              user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Vista para a lagoa maravilhosa, ambiente calmo e agradável." },
  { place: "Palaphita Kitch",        user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Ambiente ao ar livre bem monitorado, me senti seguro." },
  { place: "Melt Bar",               user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Situação de assédio ignorada pelos seguranças na entrada." },
  { place: "Maze Inn Bar",           user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Vista incrível do morro, ambiente diverso e super receptivo." },
  { place: "Baixo Gávea",           user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Área movimentada mas com boa presença de segurança." },
  { place: "Baixo Gávea",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Ponto de encontro clássico, muito agitado e divertido." },
  # Brasil - João
  { place: "Bar Brahma",             user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Ambiente histórico e muito acolhedor, nunca me senti excluído ou desconfortável por lá." },
  { place: "A Barulheira",           user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Sofri assédio verbal na fila de entrada e nenhum segurança tomou qualquer providência." },
  { place: "The Blue Pub",           user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Um dos bares mais inclusivos que já fui em SP, staff muito atencioso e diverso." },
  { place: "Clube Buena Vista",      user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Segurança bem treinada e presença constante dentro e fora do estabelecimento." },
  { place: "Bar Balcão",             user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Fui mal atendido de forma clara após demonstrar afeto pelo meu namorado." },
  { place: "Pelourinho Bar",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Lugar lindo com muita cultura local, me senti respeitado e bem-vindo durante toda a noite." },
  { place: "Beco dos Artistas",      user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Ótima iluminação, movimento saudável e equipe sempre por perto para qualquer necessidade." },
  { place: "Bar do Reggae",          user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Presenciei cenas de assédio repetidas durante a noite sem nenhuma intervenção da equipe." },
  { place: "Boteco da Praia",        user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Vista incrível do Rio Negro e atendimento super simpático, recomendo sem reservas." },
  { place: "Studio 5 Club",          user_id: joao_id,   cat: "Segurança",   status: "negative", desc: "Segurança muito negligente, presenciei situação de risco que foi completamente ignorada." },
  { place: "Bar do Ferreira",        user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Bar tradicional de Recife, pessoal muito acolhedor e ambiente sem preconceitos." },
  { place: "Baiúca Bar",             user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Funcionário fez comentário homofóbico na minha frente sem nenhum constrangimento." },
  { place: "Armazém 5",              user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Show ao vivo excelente e ambiente bem diverso, me senti muito à vontade durante toda a noite." },
  { place: "Boteco Praia de Iracema",user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Equipe bem preparada e estrutura de segurança adequada para o tamanho do local." },
  { place: "Casa de Shows Náutico",  user_id: joao_id,   cat: "Violência",   status: "negative", desc: "Testemunhei uma briga séria dentro do estabelecimento e a segurança demorou muito para agir." },
  { place: "Opinião",                user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Casa de shows referência em Porto Alegre, ambiente muito inclusivo e shows incríveis." },
  { place: "Bar Ocidente",           user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Fui assediado na pista de dança de forma insistente sem nenhuma ajuda da equipe do bar." },
  { place: "Toca da Coruja",         user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Ambiente tranquilo e bem monitorado, nunca me senti em risco em nenhuma das minhas visitas." },
  { place: "Razzmatazz Curitiba",    user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Balada muito inclusiva em Curitiba, diversidade total e sem julgamentos de nenhum tipo." },
  { place: "Bar do Victor",          user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Grupo de clientes fez piadas preconceituosas em voz alta e nenhum funcionário interveio." },
  # Brasil - Ana
  { place: "Bar Brahma",             user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Fui várias vezes e sempre me senti muito segura, a equipe é muito atenta e respeitosa." },
  { place: "A Barulheira",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Gosto muito do ambiente despojado e da diversidade de público que encontro sempre por lá." },
  { place: "The Blue Pub",           user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Ouvi comentários transfóbicos de um grupo de clientes que não foram repreendidos pela equipe." },
  { place: "Clube Buena Vista",      user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Sofri assédio físico na pista e o segurança minimizou a situação quando pedi ajuda." },
  { place: "Bar Balcão",             user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Ótimo para encontrar amigos, música boa e ambiente bem tranquilo e sem tensão nenhuma." },
  { place: "Pelourinho Bar",         user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Atendente fez comentário lesbofóbico de forma velada que me deixou muito desconfortável." },
  { place: "Beco dos Artistas",      user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Lugar muito charmoso com arte local por toda parte, me senti super bem recebida." },
  { place: "Bar do Reggae",          user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Apesar do movimento intenso a equipe de segurança estava sempre por perto e atenta." },
  { place: "Boteco da Praia",        user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Fui assediada verbalmente por outros clientes de forma repetida durante toda a noite." },
  { place: "Studio 5 Club",          user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Clube animado com boa diversidade de público, gostei bastante da experiência em geral." },
  { place: "Bar do Ferreira",        user_id: ana_id,    cat: "Violência",   status: "negative", desc: "Testemunhei uma agressão física próxima ao banheiro que deixou todos muito assustados." },
  { place: "Baiúca Bar",             user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Ambiente à beira-mar muito gostoso, atendimento simpático e sem nenhum episódio negativo." },
  { place: "Armazém 5",              user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Seguranças foram seletivos e preconceituosos na entrada, barrei junto com amigas trans." },
  { place: "Boteco Praia de Iracema",user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Vista linda do pôr do sol e clima muito descontraído, ótimo para sair sem preocupação." },
  { place: "Casa de Shows Náutico",  user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Shows grandes e estrutura de segurança adequada, me senti protegida durante todo o evento." },
  { place: "Opinião",                user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Sofri assédio persistente por parte de um cliente e a equipe não deu atenção à situação." },
  { place: "Bar Ocidente",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Bom Fim tem uma energia única e o Bar Ocidente reflete isso, muito inclusivo e divertido." },
  { place: "Toca da Coruja",         user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Fui ignorada pelo garçom enquanto mesas ao redor eram atendidas claramente por preferência." },
  { place: "Razzmatazz Curitiba",    user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Equipe de segurança bem treinada, me abordaram de forma respeitosa quando pedi ajuda." },
  { place: "Bar do Victor",          user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Lugar charmoso no centro de Curitiba, ótimo para uma saída tranquila sem preocupações." },
  # Brasil - Carlos
  { place: "Bar Brahma",             user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Funcionário foi visivelmente grosseiro após perceber que eu e meu parceiro éramos um casal." },
  { place: "A Barulheira",           user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Nunca tive problemas, segurança sempre presente e equipe muito bem treinada para a função." },
  { place: "The Blue Pub",           user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Presenciei cenas de assédio que foram completamente ignoradas pelos funcionários presentes." },
  { place: "Clube Buena Vista",      user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Melhor bar da Vila Madalena na minha opinião, ambiente super acolhedor e sem preconceito." },
  { place: "Bar Balcão",             user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Excelente estrutura, saída bem monitorada e sem situações de risco em nenhuma das visitas." },
  { place: "Pelourinho Bar",         user_id: carlos_id, cat: "Violência",   status: "negative", desc: "Assisti a uma briga que envolveu agressão física e a segurança levou muito tempo para agir." },
  { place: "Beco dos Artistas",      user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Grupo de clientes fez comentários homofóbicos em voz alta por longos minutos sem interrupção." },
  { place: "Bar do Reggae",          user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Reggae ao vivo e público muito diverso e receptivo, me senti completamente à vontade." },
  { place: "Boteco da Praia",        user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Apesar de ser em área mais periférica me senti seguro, equipe muito bem preparada." },
  { place: "Studio 5 Club",          user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Assédio recorrente na pista de dança com omissão completa da equipe de segurança presente." },
  { place: "Bar do Ferreira",        user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Bar boêmio à beira do rio com muito charme, público diverso e sem qualquer tipo de julgamento." },
  { place: "Baiúca Bar",             user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Boa estrutura de segurança para o tamanho do bar, me senti tranquilo durante toda a visita." },
  { place: "Armazém 5",              user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Fortaleza tem uma cena noturna incrível e o Armazém 5 é um dos melhores exemplos disso." },
  { place: "Boteco Praia de Iracema",user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Fui abordado de forma insistente por um cliente sem que ninguém da equipe interferisse." },
  { place: "Casa de Shows Náutico",  user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Estrutura impecável para shows, ambiente bem organizado e sem episódios negativos registrados." },
  { place: "Opinião",                user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Seguranças fizeram comentário desnecessário sobre minha aparência na entrada do evento." },
  { place: "Bar Ocidente",           user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Ótima equipe de segurança e ambiente muito bem iluminado, nunca me senti inseguro por lá." },
  { place: "Toca da Coruja",         user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Bar elegante e muito tranquilo em Moinhos de Vento, atendimento excepcional e sem incidentes." },
  { place: "Razzmatazz Curitiba",    user_id: carlos_id, cat: "Violência",   status: "negative", desc: "Presenciei uma confusão séria próxima à saída que assustou muita gente, mal gerenciada." },
  { place: "Bar do Victor",          user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Centro de Curitiba e mesmo assim me senti seguro a noite toda, boa estrutura de controle." },
  # Novos lugares - João
  { place: "Bar Beirute BH",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Clássico de BH, ambiente muito acolhedor e diverso, frequento há anos sem nenhum problema." },
  { place: "Café com Letras",        user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Espaço cultural incrível em BH, muito inclusivo e com eventos para todos os públicos." },
  { place: "Bukowski BH",            user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Sofri assédio verbal na fila e a equipe não tomou nenhuma atitude quando relatei." },
  { place: "Manifesto Bar",          user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Nome condiz com a proposta, ambiente muito político e acolhedor para a diversidade." },
  { place: "Bar Brasília",           user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Bar tradicional de Brasília, equipe bem treinada e ambiente sem nenhum tipo de tensão." },
  { place: "Clube do Choro",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Música ao vivo maravilhosa e ambiente muito respeitoso, me senti completamente à vontade." },
  { place: "Antro Pub",              user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Ouvi comentários homofóbicos de um grupo de clientes que não foram repreendidos por ninguém." },
  { place: "Hangar 110",             user_id: joao_id,   cat: "Violência",   status: "negative", desc: "Presenciei uma briga séria no banheiro que a segurança demorou muito tempo para conter." },
  { place: "John Bull Pub",          user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Pub inglês muito charmoso em Floripa, público diverso e equipe super receptiva." },
  { place: "Bar do Ataliba",         user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Local tranquilo no centro de Florianópolis, me senti seguro em todas as minhas visitas." },
  { place: "Dado Bier Floripa",      user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Estrutura ótima, ambiente bem organizado e sem nenhum episódio negativo que eu tenha presenciado." },
  { place: "Goianésia Bar",          user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Assédio recorrente na pista sem qualquer intervenção da equipe de segurança do local." },
  { place: "Aramará Bar",            user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Ótimo bar no Setor Bueno, público diverso e atendimento excelente em todas as visitas." },
  { place: "Ver-o-Peso Bar",         user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Ambiente à beira do porto muito charmoso e bem monitorado, me senti seguro a noite toda." },
  { place: "Estação das Docas",      user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Estrutura impecável em Belém, muito inclusivo e com ótima programação cultural noturna." },
  { place: "Bar do Meio",            user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Funcionário fez piada preconceituosa sobre minha aparência na frente de outros clientes." },
  { place: "Barcas Bar",             user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Vista linda para o mar em Natal, ambiente descontraído e público bem diverso e receptivo." },
  { place: "Slow Bar",               user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Bar tranquilo em João Pessoa, equipe sempre atenta e ambiente sem nenhum tipo de tensão." },
  { place: "Café Epitácio",          user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Frente ao mar em Tambaú, ótimo para uma saída segura e relaxada com amigos ou casal." },
  { place: "Jaraguá Bar",            user_id: joao_id,   cat: "Violência",   status: "negative", desc: "Testemunhei agressão física próxima à saída sem nenhuma reação rápida da segurança." },
  { place: "Bar do Francis",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Jatiúca tem ótimos bares e esse é um dos melhores, ambiente muito acolhedor e inclusivo." },
  { place: "Buritis Bar",            user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Campo Grande tem uma cena noturna crescente e o Buritis é referência de ambiente seguro." },
  { place: "Bar Central Vitória",    user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Centro histórico de Vitória tem muito charme, bar acolhedor e sem nenhum episódio negativo." },
  { place: "Bohemia Club",           user_id: joao_id,   cat: "Assédio",     status: "negative", desc: "Assédio físico na pista e segurança recusou ajuda dizendo que era brincadeira entre conhecidos." },
  { place: "Antigamente Bar",        user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Centro histórico de São Luís é lindo e o bar reflete isso com ambiente muito acolhedor." },
  { place: "Bar do Nelson",          user_id: joao_id,   cat: "Segurança",   status: "positive", desc: "Beira-mar do Calhau com boa estrutura de segurança, me senti tranquilo durante toda a noite." },
  { place: "Casa Mágica",            user_id: joao_id,   cat: "Preconceito", status: "negative", desc: "Atendimento claramente diferenciado para pessoas LGBTQ+, situação muito desconfortável." },
  { place: "Quixabeira Bar",         user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Pituba é o bairro mais animado de Salvador, bar com ótimo ambiente e público diverso." },
  { place: "Ó do Borogodó",          user_id: joao_id,   cat: "Ambiente",    status: "positive", desc: "Samba na Lapa paulistana com muito charme, ambiente acolhedor e sem nenhum tipo de preconceito." },
  # Novos lugares - Ana
  { place: "Bar Beirute BH",         user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Fui ignorada pelo garçom de forma sistemática enquanto homens ao redor eram atendidos rapidamente." },
  { place: "Café com Letras",        user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Espaço muito seguro e bem iluminado, equipe atenta e nunca tive nenhum problema por lá." },
  { place: "Bukowski BH",            user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Gosto muito do ambiente alternativo do Bukowski BH, muito inclusivo e sem julgamentos." },
  { place: "Bar Brasília",           user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Fui assediada de forma insistente e o segurança disse que eu devia estar exagerando na situação." },
  { place: "Clube do Choro",         user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Música ao vivo incrível e público muito respeitoso, uma das melhores experiências que tive." },
  { place: "Antro Pub",              user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Pub animado com equipe de segurança bem presente, me senti protegida durante toda a noite." },
  { place: "John Bull Pub",          user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Comentário lesbofóbico de um funcionário na hora de atender, situação horrível e constrangedora." },
  { place: "Bar do Ataliba",         user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Lugar super charmoso no centro de Floripa, público diverso e atendimento sem nenhum problema." },
  { place: "Goianésia Bar",          user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Goiânia tem evoluído muito e o Goianésia reflete isso com ambiente bem monitorado e seguro." },
  { place: "Ver-o-Peso Bar",         user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Assédio verbal por parte de um grupo de clientes que a equipe se recusou a retirar do local." },
  { place: "Estação das Docas",      user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Uma das experiências mais agradáveis que tive no Norte do Brasil, muito inclusivo e bonito." },
  { place: "Bar do Meio",            user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Equipe bem treinada em Natal, ambiente seguro e nunca presenciei nenhuma situação de risco." },
  { place: "Slow Bar",               user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Bar alternativo muito bacana em João Pessoa, ótima programação e ambiente totalmente inclusivo." },
  { place: "Jaraguá Bar",            user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "O bairro Jaraguá tem muita história e o bar reflete isso com ambiente acolhedor e diverso." },
  { place: "Buritis Bar",            user_id: ana_id,    cat: "Preconceito", status: "negative", desc: "Seguranças fizeram comentário sobre minha roupa na entrada de forma claramente discriminatória." },
  { place: "Bar Central Vitória",    user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Centro de Vitória com boa estrutura de segurança, equipe presente e atenta a tudo." },
  { place: "Bohemia Club",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Praia do Canto é ótima em Vitória e o Bohemia tem ambiente muito agradável e sem problemas." },
  { place: "Antigamente Bar",        user_id: ana_id,    cat: "Violência",   status: "negative", desc: "Presenciei cena de violência verbal grave que a equipe demorou muito para controlar." },
  { place: "Bar do Nelson",          user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Melhor experiência que tive em São Luís, vista linda do calhau e ambiente muito tranquilo." },
  { place: "Quixabeira Bar",         user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Assédio constante na pista sem que nenhum funcionário tivesse tomado qualquer providência." },
  { place: "Ó do Borogodó",          user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Samba de raiz em SP com muito respeito e diversidade, me senti completamente à vontade." },
  { place: "Bar Bukowski",           user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Copacabana pode ser intensa mas o Bukowski tem boa estrutura de segurança e equipe preparada." },
  { place: "Barzin",                 user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Referência LGBTQ+ em Ipanema, ambiente super acolhedor e sem qualquer tipo de preconceito." },
  { place: "Venga!",                 user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Staff incrível, sempre atentos a qualquer situação, me senti muito segura em todas as visitas." },
  { place: "The Week Rio",           user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Seguranças fizeram seleção claramente discriminatória na porta com base na aparência das pessoas." },
  { place: "Cine Joia",              user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Shows incríveis no centro do Rio com ambiente muito diverso e equipe sempre atenta ao público." },
  { place: "Bar dos Descasados",     user_id: ana_id,    cat: "Assédio",     status: "negative", desc: "Sofri assédio em Santa Teresa e ninguém da equipe tomou atitude mesmo quando pedi ajuda." },
  { place: "Mirindiba",              user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Santa Teresa encanta e o Mirindiba mais ainda, ambiente charmoso e totalmente inclusivo." },
  { place: "Bar Lagoa",              user_id: ana_id,    cat: "Segurança",   status: "positive", desc: "Vista linda para a Lagoa Rodrigo de Freitas com equipe atenta e ambiente muito tranquilo." },
  { place: "Maze Inn Bar",           user_id: ana_id,    cat: "Ambiente",    status: "positive", desc: "Vista do Catete é linda e o bar tem um clima muito especial, público diverso e acolhedor." },
  # Novos lugares - Carlos
  { place: "Manifesto Bar",          user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Savassi é animado e o Manifesto tem boa estrutura de segurança, me senti tranquilo a noite toda." },
  { place: "Bukowski BH",            user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Nunca tive problemas no Bukowski BH, equipe sempre presente e atenta a qualquer situação." },
  { place: "Café com Letras",        user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Atendente fez comentário desnecessário sobre minha aparência na frente de outros clientes." },
  { place: "Hangar 110",             user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Estrutura impressionante em Brasília, ambiente bem diverso e equipe muito bem preparada." },
  { place: "Antro Pub",              user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Um dos melhores pubs de Brasília, alternativo e muito inclusivo, nunca tive problemas." },
  { place: "Bar Brasília",           user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Funcionário foi claramente discriminatório ao nos atender depois de ver que éramos um casal." },
  { place: "Dado Bier Floripa",      user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Estrutura muito boa em Florianópolis, equipe bem treinada e ambiente sem situações de risco." },
  { place: "Bar do Ataliba",         user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Sofri assédio verbal no banheiro e ao reclamar o funcionário disse que eu havia entendido errado." },
  { place: "Aramará Bar",            user_id: carlos_id, cat: "Violência",   status: "negative", desc: "Briga entre clientes com chutes e socos e a segurança demorou minutos para aparecer e agir." },
  { place: "Estação das Docas",      user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Complexo bem organizado em Belém com boa segurança, me senti protegido durante toda a visita." },
  { place: "Ver-o-Peso Bar",         user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Experiência única à beira do porto histórico de Belém, ambiente muito acolhedor e inclusivo." },
  { place: "Barcas Bar",             user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Grupo de clientes fez comentários homofóbicos altos sem que nenhum funcionário intervisse." },
  { place: "Bar do Meio",            user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Barzinho simples e muito gostoso em Natal, público diverso e atendimento sem nenhum problema." },
  { place: "Café Epitácio",          user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Assédio insistente por parte de um cliente que a equipe ignorou completamente durante horas." },
  { place: "Bar do Francis",         user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Jatiúca é animado e o Bar do Francis tem boa estrutura de segurança para o tamanho do local." },
  { place: "Pub 540",                user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Campo Grande surpreende com esse pub muito animado e ambiente bem inclusivo e diverso." },
  { place: "Buritis Bar",            user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Um dos melhores bares de Campo Grande, ambiente acolhedor e nunca presenciei episódio negativo." },
  { place: "Bohemia Club",           user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Vitória tem uma cena noturna incrível e o Bohemia é referência de segurança e bom ambiente." },
  { place: "Antigamente Bar",        user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "São Luís tem uma magia única e o Antigamente captura isso muito bem, ambiente acolhedor." },
  { place: "Casa Mágica",            user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Centro histórico de São Luís bem monitorado, equipe atenta e ambiente sem situações de risco." },
  { place: "Quixabeira Bar",         user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Pituba é o coração noturno de Salvador e o Quixabeira tem o melhor ambiente do bairro." },
  { place: "Ó do Borogodó",          user_id: carlos_id, cat: "Preconceito", status: "negative", desc: "Segurança recusou entrada de amigos trans sem qualquer justificativa plausível ou explicação." },
  { place: "Club Fosfobox",          user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Clube icônico de Copacabana com público muito diverso e ambiente que respeita todos." },
  { place: "La Carioca Cevicheria",  user_id: carlos_id, cat: "Segurança",   status: "positive", desc: "Leblon tem fama de exclusivo mas o La Carioca é bem tranquilo e a equipe é sempre atenta." },
  { place: "Bar Urca",               user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Vista da Baía de Guanabara incomparável, ambiente familiar e super tranquilo sem incidentes." },
  { place: "Lapa 40 Graus",          user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Assédio na pista ignorado pela equipe mesmo depois de eu ter pedido ajuda explicitamente." },
  { place: "Jobi Bar",               user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Botequim clássico do Leblon, pessoal super simpático e ambiente sem nenhuma tensão ou problema." },
  { place: "Palaphita Kitch",        user_id: carlos_id, cat: "Assédio",     status: "negative", desc: "Fui assediado verbalmente de forma insistente e o segurança se recusou a intervir na situação." },
  { place: "Clube dos Democratas",   user_id: carlos_id, cat: "Ambiente",    status: "positive", desc: "Baile de carnaval com muita diversidade e alegria, equipe bem preparada e ambiente acolhedor." },
  { place: "Choperia Bracarense",    user_id: carlos_id, cat: "Violência",   status: "negative", desc: "Testemunhei agressão física grave dentro do estabelecimento sem resposta rápida da segurança." }
]

# Filtra só os reports que ainda não existem e faz insert em bloco
new_reports = all_reports.filter_map do |r|
  pid = place_ids[r[:place]]
  next if pid.nil? || existing_reports.include?([pid, r[:user_id]])
  { place_id: pid, user_id: r[:user_id], category: r[:cat], status: r[:status],
    description: r[:desc], created_at: now, updated_at: now }
end

Report.insert_all(new_reports) if new_reports.any?
